name: Build Electron App
on: push
permissions:
  contents: write

jobs:
  build-01:
    if: "contains(github.event.head_commit.message, '01')"
    name: æ‰“åŒ… Electron åº”ç”¨
    runs-on: windows-latest
    steps:
      - name: å¯¼å…¥ä»£ç 
        uses: actions/checkout@v4

      - name: å‡†å¤‡Nodeç¯å¢ƒ
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: å®‰è£…ä¾èµ–
        run: |
          cd 01-Dark-Mode
          npm install

      - name: æ‰“åŒ…åº”ç”¨
        run: |
          cd 01-Dark-Mode
          npm run make

      - name: ä¸Šä¼ æ‰“åŒ…æ–‡ä»¶
        uses: actions/upload-artifact@v4
        with:
          name: electron-dark-mode
          path: 01-Dark-Mode/out


      - name: åˆ›å»º Release
        uses: softprops/action-gh-release@v2
        with:
          files: 01-Dark-Mode/out/make/squirrel.windows/x64/dark-mode-1.0.0 Setup.exe
          tag_name: 01-Dark-Mode
          body: 01-Dark-Mode
  deploy:
    if: "contains(github.event.head_commit.message, '01')"
    concurrency: ci-${{ github.ref }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Download Artifacts ğŸ”»
        uses: actions/download-artifact@v4
        with:
          name: electron-dark-mode

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'electron-dark-mode'


